{{- if and .Values.rbac.create .Values.rbac.clusterWide }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ruleraven.fullname" . }}-watcher
  labels:
    {{- include "ruleraven.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ruleraven.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ruleraven.fullname" . }}-watcher
{{- end }}
